name: PerfAI Super Action
description: PerfAI Super Action as part of your GitHub Actions workflow.
author: PerfAI, Inc.
branding:
  icon: "package"
  color: "gray-dark"
      
inputs:
  username:
    description: 'PerfAI Username'
    required: true
  password:
    description: 'PerfAI Password'
    required: true
  openapi_url:
    description: 'OpenAPI Specification/Swagger/Bulk/Zip URLs'
    required: true
  base_path:
    description: 'Server base path for the API'
    required: true
  api_id:
    description: 'API Id generated for PerfAI'
    required: true
  label:
    description: 'API label name'
    required: true
  wait-for-completion:
    description: 'To wait till PerfAI tests complete, set to `true`'
    required: false
    default: "true"
  fail-on-new-leaks:
    description: 'To fail the build on new leaks introduced with this commit, set to `true`.'
    required: false
    default: "false"
  auth_url_1:
    description: 'Authentication URL for Test Account 1'
    required: false
  auth_body_1:
    description: 'Authentication body for Test Account 1'
    required: false   
  auth_headers:
    description: 'Authorization headers for authentication'
    required: false
  auth_url_2:
    description: 'Authentication URL for Test Account 2'
    required: false
  auth_body_2:
    description: 'Authentication body for Test Account 2'
    required: false

runs:
  using: "composite"
  steps:
    - name: Grant execute permission for action-run.sh
      run: chmod +x ${GITHUB_ACTION_PATH}/action-run.sh
      shell: bash
      
    - name: Run action-run.sh
      run: |
        ${GITHUB_ACTION_PATH}/action-run.sh --username "${{ inputs.username }}" --password "${{ inputs.password }}" --openapi_url "${{ inputs.openapi_url }}" --base_path "${{ inputs.base_path }}" --api_id "${{ inputs.api_id }}" --label "${{ inputs.label }}" --wait-for-completion "${{ inputs.wait-for-completion }}" --fail-on-new-leaks "${{ inputs.perfai-fail-on-new-leaks }} --auth_url_1 "${{ inputs.auth_url_1 }}" --auth_body_1 "${{ inputs.auth_body_1 }}" --auth_headers "${{ inputs.auth_headers }}" --auth_url_2 "${{ inputs.auth_url_2 }}" --auth_body_2 "${{ inputs.auth_body_2 }}"
      shell: bash
