name: PerfAI Super Action
description: PerfAI Super Action as part of your GitHub Actions workflow.
author: PerfAI Super, Inc.
branding:
  icon: "package"
  color: "gray-dark"
      
inputs:
  username:
    description: 'API Privacy Username'
    required: true
  password:
    description: 'API Privacy Password'
    required: true
  api-id:
    description: 'API Id generated for the API in API Privacy'
    required: true
  api-name:
    description: 'API name/label'
    required: true
  wait-for-completion:
    description: 'To wait till the tests gets completed, set to `true` '
    required: false
    default: "false"
  fail-on-new-leaks:
    description: 'To fail the build on new leaks introduced with this commit, set to `true`.'
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Grant execute permission for action-run.sh
      run: chmod +x ${GITHUB_ACTION_PATH}/action-run.sh
      shell: bash
      
    - name: Run action-run.sh
      run: |
        ${GITHUB_ACTION_PATH}/action-run.sh --username "${{ inputs.username }}" --password "${{ inputs.password }}" --catalog-id "${{ inputs.api-id }}" --wait-for-completion "${{ inputs.wait-for-completion }}" --fail-on-new-leaks "${{ inputs.fail-on-new-leaks}}"
      shell: bash
